CREATE TABLE books(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255),
	pages INT
);

CREATE TABLE authors(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255),
	age INT,
	book_id INT UNIQUE NOT NULL
	
	, CONSTRAINT book_author_fk FOREIGN KEY(book_id) REFERENCES books(id)
);
